name: codecascade
description: "Application e-learning CODECASCADE"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  file_picker: ^10.3.10
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  
flutter_native_splash:
  color: "#0F172A"
  image: assets/images/logo.png

  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # AJOUTE CECI ↓↓↓
  assets:
    - assets/images/splash_background.png
  
  # Optionnel: Ajouter des polices personnalisées plus tard
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700