// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUBYOfgKJZDJtcnrrLGo8h4VDtEIMQWO4',
    appId: '1:412517173233:web:c36a3590cbf7ab21cbe650',
    messagingSenderId: '412517173233',
    projectId: 'codecascade-52984',
    authDomain: 'codecascade-52984.firebaseapp.com',
    storageBucket: 'codecascade-52984.firebasestorage.app',
    measurementId: 'G-DJC0C57F5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6cEDeTFgLMYVkFRZP8VCIiLu4nj2UQVA',
    appId: '1:412517173233:android:4e5e897c06e8cd31cbe650',
    messagingSenderId: '412517173233',
    projectId: 'codecascade-52984',
    storageBucket: 'codecascade-52984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFv1j7TNkhcrWCYFesC6RcKfJ9DbpgR7o',
    appId: '1:412517173233:ios:8cfd316f5976573dcbe650',
    messagingSenderId: '412517173233',
    projectId: 'codecascade-52984',
    storageBucket: 'codecascade-52984.firebasestorage.app',
    androidClientId: '412517173233-7q3ujoj6tqnmbi05q39mpdlp5qlqhr8u.apps.googleusercontent.com',
    iosClientId: '412517173233-f7rkn7tupjmkfrndre89rru3b4s2agep.apps.googleusercontent.com',
    iosBundleId: 'com.example.codecascade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFv1j7TNkhcrWCYFesC6RcKfJ9DbpgR7o',
    appId: '1:412517173233:ios:8cfd316f5976573dcbe650',
    messagingSenderId: '412517173233',
    projectId: 'codecascade-52984',
    storageBucket: 'codecascade-52984.firebasestorage.app',
    androidClientId: '412517173233-7q3ujoj6tqnmbi05q39mpdlp5qlqhr8u.apps.googleusercontent.com',
    iosClientId: '412517173233-f7rkn7tupjmkfrndre89rru3b4s2agep.apps.googleusercontent.com',
    iosBundleId: 'com.example.codecascade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUBYOfgKJZDJtcnrrLGo8h4VDtEIMQWO4',
    appId: '1:412517173233:web:af490f286f582dafcbe650',
    messagingSenderId: '412517173233',
    projectId: 'codecascade-52984',
    authDomain: 'codecascade-52984.firebaseapp.com',
    storageBucket: 'codecascade-52984.firebasestorage.app',
    measurementId: 'G-57BHSGKYTX',
  );
}
